version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    image: "fastapi_dev"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app:cached
    env_file:
      - .env
    ports:
      - 8000:8000
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: "fastapi_dev_postgres"
    volumes:
      - dev_postgres:/var/lib/postgresql/data:Z
      - dev_backups:/backups:z
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # minio: # Use minio for local S3 storage
  #   image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #     MINIO_ACCESS_KEY: test-keys
  #     MINIO_SECRET_KEY: test-superkey
  #   volumes:
  #     - ./data/dev_minio:/data

volumes:
  dev_postgres:
  dev_backups:
